# ORDER MATTERS IN THIS FILE
# IMPORT BASIC STUFF FIRST
from .transformation import TransformationSet,Transformation,IdentityTransformation

from .measure import MeasureResult, StratifiedMeasureResult

from .numpy.base import NumpyMeasure

from .numpy.functions import MeasureFunction
from .numpy.layer_transformation import ConvAggregation
from .numpy.quotient import QuotientMeasure,divide_activations


from transformation_measure.activations_iterator import ActivationsIterator
from transformation_measure.pytorch import *

from .numpy.multithreaded_layer_measure import PerLayerMeasure,LayerMeasure,SamplesFirstPerLayerMeasure,TransformationsFirstPerLayerMeasure

from .numpy.multithreaded_variance import TransformationVarianceMeasure,SampleVarianceMeasure,NormalizedVarianceMeasure
from .numpy.normalized import NormalizedVariance,SampleVariance,TransformationVariance
from .numpy.anova import AnovaMeasure,AnovaFMeasure
from .numpy.distance import NormalizedDistance,SampleDistance,TransformationDistance,DistanceAggregation

from .numpy.distance_equivariance import NormalizedDistanceSameEquivariance,TransformationDistanceSameEquivariance,SampleDistanceSameEquivariance

from .numpy.variance_same_equivariance import NormalizedVarianceSameEquivariance,TransformationVarianceSameEquivariance,SampleVarianceSameEquivariance

from .numpy.same_equivariance_simple import DistanceSameEquivarianceSimple,DistanceFunction


from .numpy.goodfellow import GoodfellowMeasure
from .numpy.goodfellow_prob import GoodfellowNormal,GoodfellowLocalVarianceNormal,GoodfellowGlobalVarianceNormal

from .adapters import TransformationAdapter,PytorchNumpyImageTransformationAdapter,NumpyPytorchImageTransformationAdapter

from transformation_measure import language

def set_language(l:language.Language):
    language.l=l