name: Setup Project
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: Install dependencies
    run: sudo apt install graphviz-dev
    shell: bash
  
  - name: Install uv
    uses: astral-sh/setup-uv@v5
    with:
        enable-cache: true

  - name: "Set up Python"
    uses: actions/setup-python@v5
    with:
      python-version-file: "pyproject.toml"

  - name: Install the project
    run: uv sync
    shell: bash

  - name: Install poe the poet
    run: uv tool install poethepoet
    shell: bash
